name: mall_nav_app
description: A mall navigation app with object detection
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.31.15
  flutter_tts: ^3.8.5
  camera: ^0.10.5+9
  google_mlkit_object_detection: ^0.11.0
  google_mlkit_commons: ^0.6.1
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 